create table "user"
(
    id          bigint generated by default as identity,
    create_time timestamp(6),
    creator     bigint,
    is_deleted  boolean,
    update_time timestamp(6),
    updater     bigint,
    activated   boolean      not null,
    password    varchar(100) not null,
    username    varchar(100) not null,
    primary key (id)
);

create table authority
(
    name varchar(50) not null,
    primary key (name)
);

create table user_authority
(
    user_id        bigint      not null,
    authority_name varchar(50) not null,
    primary key (user_id, authority_name)
);

create table points_account
(
    id           bigint generated by default as identity,
    create_time  timestamp(6),
    creator      bigint,
    is_deleted   boolean,
    update_time  timestamp(6),
    updater      bigint,
    user_id      bigint       not null,
    total_points integer      not null,
    frozen_points integer      not null,
    primary key (id),
    constraint uk_points_account_user_id unique (user_id),
    constraint fk_points_account_user foreign key (user_id) references "user" (id)
);

create table points_rule
(
    id           bigint generated by default as identity,
    create_time  timestamp(6),
    creator      bigint,
    is_deleted   boolean,
    update_time  timestamp(6),
    updater      bigint,
    channel_type varchar(50)  not null,
    ratio        double       not null,
    expire_days  integer      not null,
    description  text,
    is_enabled   boolean      not null,
    creator_id   bigint,
    updater_id   bigint,
    primary key (id)
);

create table points_record
(
    id           bigint generated by default as identity,
    create_time  timestamp(6),
    creator      bigint,
    is_deleted   boolean,
    update_time  timestamp(6),
    updater      bigint,
    user_id      bigint       not null,
    type         varchar(20)  not null,
    points       integer      not null,
    biz_id       varchar(100),
    channel_type varchar(50),
    description  text,
    record_time  timestamp(6) not null,
    primary key (id),
    constraint fk_points_record_user foreign key (user_id) references "user" (id)
);

create table points_batch
(
    id             bigint generated by default as identity,
    create_time    timestamp(6),
    creator        bigint,
    is_deleted     boolean,
    update_time    timestamp(6),
    updater        bigint,
    user_id        bigint       not null,
    points         integer      not null,
    expire_time    timestamp(6),
    frozen_points  integer      not null,
    available_points integer    not null,
    record_id      bigint       not null,
    temp_order_id  varchar(100),
    primary key (id),
    constraint fk_points_batch_user foreign key (user_id) references "user" (id),
    constraint fk_points_batch_record foreign key (record_id) references points_record (id)
);

create table wallet
(
    id                  bigint generated by default as identity,
    create_time         timestamp(6),
    creator             bigint,
    is_deleted          boolean,
    update_time         timestamp(6),
    updater             bigint,
    owner_id            bigint       not null,
    balance             numeric(19,2) not null,
    voucher             numeric(19,2) not null,
    credit_limit        numeric(19,2) not null default 0,
    last_withdrawal_at  timestamp(6),
    primary key (id),
    constraint uk_wallet_owner_id unique (owner_id),
    constraint fk_wallet_user foreign key (owner_id) references "user" (id)
);
