spring.application.name=cart-service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${DB_URL:jdbc:mysql://mysql:3306/elm_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:elm}
spring.datasource.password=${DB_PASSWORD:elm}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

server.port=8086
server.servlet.context-path=/elm

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
