spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:${CONFIG_REPO_PATH:/root/workspace/TJU-SE-Practice-2/spring-cloud-config-repo}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
