server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/elm/api/authenticate, /elm/api/register, /elm/api/account/**, /elm/api/users/**, /elm/api/user, /elm/api/password, /elm/api/persons/**, /elm/api/auth/**

        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/elm/api/wallet/**, /elm/api/transactions/**, /elm/api/vouchers/**, /elm/api/transaction/**, /elm/api/publicVoucher/**, /elm/api/privateVoucher/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/elm/api/orders/**, /elm/api/reviews/**

        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/elm/api/addresses/**

        - id: merchant-service
          uri: lb://merchant-service
          predicates:
            - Path=/elm/api/businesses/**, /elm/api/applications/business/**, /elm/api/applications/merchant/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/elm/api/foods/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/elm/api/carts, /elm/api/carts/**, /elm/carts, /elm/carts/**, /elm/internal/carts/**

        - id: points-service
          uri: lb://points-service
          predicates:
            - Path=/elm/api/points/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh, refresh
  endpoint:
    health:
      show-details: always
